version: '3.9'
services:
  nfs-server:
    build:
      context: .
      dockerfile: dockerfile-nfs-server
    platform: linux/arm64/v8 # uncomment for Apple Silicon arch
    image: christophermiliotis/nfs-server
    privileged: true
    container_name: nfs-server
    environment:
      NFS_LOG_LEVEL: DEBUG
    hostname: nfs-server
    healthcheck:
      test: ["CMD-SHELL", "sleep 5"] # required, otherwise the nfs-client service will fail to start with a "connection refused" error
      interval: 1s
      timeout: 1m
      retries: 10
    ports:
      - 2049:2049
    networks:
      nfs-server-bridge:
        ipv4_address: 192.168.1.2
    volumes:
      - nfs-server-volume:/var/gerrit/git
  gerrit1:
    build: ../gerrit
    networks:
      nfs-server-bridge: null
    ports:
      - 8080:8080
      - 29418:29418
    volumes:
      - ../primary-replica/primary/etc:/var/gerrit/etc:rw
      - ../primary-replica/primary/logs:/var/gerrit/logs:rw
      - ../primary-replica/replication_ssh_keys/replication_user_id_rsa:/home/gerrit/.ssh/id_rsa:rw
      - ../primary-replica/ssh/config:/home/gerrit/.ssh/config:rw
      - ../primary-replica/primary/git:/var/gerrit/git-replica:rw
  gerrit2:
    depends_on:
      nfs-server:
        condition: service_healthy
        restart: true
    build: ../gerrit
    privileged: true
    networks:
      nfs-server-bridge: null
    ports:
      - 8081:8080
      - 29419:29418
    volumes:
      - ../primary-replica/replica/etc:/var/gerrit/etc:rw
      - ../primary-replica/replica/logs:/var/gerrit/logs:rw
      - nfs-client-volume:/var/gerrit/git

volumes:
  nfs-server-volume:
    name: nfs-server-volume
  nfs-client-volume:
    name: nfs-client-volume
    driver: "local"
    driver_opts:
      type: nfs
      o: "addr=192.168.1.2,rw"
      device: ":/var/gerrit/git"
networks:
  nfs-server-bridge:
    name: nfs-server-bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
